name: DepoChests
main: com.bugfullabs.depochests.DepoChests
version: 0.0.5
author: Grushenko

commands:
   depochests:
      description: Basic DepoChests command.
      usage: /<command>
      permission: <plugin name>.depochests
      permission-message: You don't have <permission>
   
