name: DepoChests
main: com.bugfullabs.depochests.DepoChests
version: 0.3.3
author: Grushenko

commands:
   depochests:
      description: Basic DepoChests command.
      usage: /<command>
      permission: depochests.depochests
      permission-message: You are not allowed to use this command.
   depo:
      description: Opens DepoChest.
      usage: /<command>
      permission: depochests.depo
      permission-message: You are not allowed to use this command.  
      
      
permissions:
    depochests.*:
        description: Gives access to all DepoChests commands
        children:
            depochests.depochests: true
            depochests.depo: true
    depochests.depochests:
        description: Allows you to perform DepoChests admin commands.
        default: op
    depochests.depo:
        description: Allows you to open your DepoChest using a command.
        default: op
  